/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerfRouteImport } from './routes/perf'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PProjectIdRouteImport } from './routes/p.$projectId'
import { Route as ApiBridgeStreamRouteImport } from './routes/api.bridge.stream'
import { Route as ApiBridgeResultRouteImport } from './routes/api.bridge.result'

const PerfRoute = PerfRouteImport.update({
  id: '/perf',
  path: '/perf',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIdRoute = PProjectIdRouteImport.update({
  id: '/p/$projectId',
  path: '/p/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBridgeStreamRoute = ApiBridgeStreamRouteImport.update({
  id: '/api/bridge/stream',
  path: '/api/bridge/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBridgeResultRoute = ApiBridgeResultRouteImport.update({
  id: '/api/bridge/result',
  path: '/api/bridge/result',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/perf': typeof PerfRoute
  '/p/$projectId': typeof PProjectIdRoute
  '/api/bridge/result': typeof ApiBridgeResultRoute
  '/api/bridge/stream': typeof ApiBridgeStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/perf': typeof PerfRoute
  '/p/$projectId': typeof PProjectIdRoute
  '/api/bridge/result': typeof ApiBridgeResultRoute
  '/api/bridge/stream': typeof ApiBridgeStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/perf': typeof PerfRoute
  '/p/$projectId': typeof PProjectIdRoute
  '/api/bridge/result': typeof ApiBridgeResultRoute
  '/api/bridge/stream': typeof ApiBridgeStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/perf'
    | '/p/$projectId'
    | '/api/bridge/result'
    | '/api/bridge/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/perf'
    | '/p/$projectId'
    | '/api/bridge/result'
    | '/api/bridge/stream'
  id:
    | '__root__'
    | '/'
    | '/mcp'
    | '/perf'
    | '/p/$projectId'
    | '/api/bridge/result'
    | '/api/bridge/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  McpRoute: typeof McpRoute
  PerfRoute: typeof PerfRoute
  PProjectIdRoute: typeof PProjectIdRoute
  ApiBridgeResultRoute: typeof ApiBridgeResultRoute
  ApiBridgeStreamRoute: typeof ApiBridgeStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/perf': {
      id: '/perf'
      path: '/perf'
      fullPath: '/perf'
      preLoaderRoute: typeof PerfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$projectId': {
      id: '/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/p/$projectId'
      preLoaderRoute: typeof PProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bridge/stream': {
      id: '/api/bridge/stream'
      path: '/api/bridge/stream'
      fullPath: '/api/bridge/stream'
      preLoaderRoute: typeof ApiBridgeStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bridge/result': {
      id: '/api/bridge/result'
      path: '/api/bridge/result'
      fullPath: '/api/bridge/result'
      preLoaderRoute: typeof ApiBridgeResultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  McpRoute: McpRoute,
  PerfRoute: PerfRoute,
  PProjectIdRoute: PProjectIdRoute,
  ApiBridgeResultRoute: ApiBridgeResultRoute,
  ApiBridgeStreamRoute: ApiBridgeStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
